[mgr]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = true
scrolloff = 5

[preview]
tab_size = 2
max_width = 1600
max_height = 1200

[opener]
edit = [
  { run = 'fresh "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$1"', orphan = true, desc = "Open" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', orphan = true, desc = "Reveal" },
]

[open]
prepend_rules = [
  { name = "*.md", use = "edit" },
  { mime = "text/*", use = "edit" },
]
